apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookreview-client
  template:
    metadata:
      labels:
        app: bookreview-client
    spec:
      containers:
        - name: client
          image: masapath/book-review-client:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookreview-client
spec:
  type: NodePort
  selector:
    app: bookreview-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
